include(FetchContent)



if("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Darwin" AND ("${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "arm64" OR "${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "aarch64"))
    set(CONTINUUM_LLVM_PLATFORM "macos-arm64")
    set(CONTINUUM_LLVM_ARCHIVE_NAME "LLVM-22.1.8-macOS-ARM64.tar.xz")
    set(CONTINUUM_LLVM_SDK_NAME "LLVM-22.1.8-macOS-ARM64")
    set(CONTINUUM_LLVM_ARCHIVE_SHA256 "f260f4f7c0d430828a81ae8a3826a1d63fc0963ec2459489308cc23b1f7eab4f")

elseif("${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Windows" AND ("${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "AMD64" OR "${CMAKE_HOST_SYSTEM_PROCESSOR}" STREQUAL "x86_64"))
    set(CONTINUUM_LLVM_PLATFORM "windows-x64")
    set(CONTINUUM_LLVM_ARCHIVE_NAME "clang+llvm-22.1.8-x86_64-pc-windows-msvc.tar.xz")
    set(CONTINUUM_LLVM_SDK_NAME "clang+llvm-22.1.8-x86_64-pc-windows-msvc")
    set(CONTINUUM_LLVM_ARCHIVE_SHA256 "d96c2cc1736f4eb7fa43cb9bbdf56d93551a9ae0a9aadb9c99c3c3b2b712a234")

else()
    message(FATAL_ERROR "Not supported platform")
endif()

set(CONTINUUM_LLVM_ARCHIVE_URL "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/${CONTINUUM_LLVM_ARCHIVE_NAME}")
set(CONTINUUM_LLVM_DOWNLOAD_DIR "${CMAKE_CURRENT_LIST_DIR}/../third_party/llvm/downloads")
set(CONTINUUM_LLVM_ARCHIVE_PATH "${CONTINUUM_LLVM_DOWNLOAD_DIR}/${CONTINUUM_LLVM_ARCHIVE_NAME}")

file(MAKE_DIRECTORY "${CONTINUUM_LLVM_DOWNLOAD_DIR}")

set(CONTINUUM_LLVM_SDK_DESTINATION_PATH "${CMAKE_CURRENT_LIST_DIR}/../third_party/llvm")
set(CONTINUUM_LLVM_SDK_PATH "${CONTINUUM_LLVM_SDK_DESTINATION_PATH}/${CONTINUUM_LLVM_SDK_NAME}")
set(CONTINUUM_LLVM_SDK_SUM_PATH "${CONTINUUM_LLVM_SDK_PATH}/.continuum_llvm_ready")

set(NEED_TO_UPDATE_LLVM OFF)

if(NOT EXISTS "${CONTINUUM_LLVM_SDK_SUM_PATH}")
    set(NEED_TO_UPDATE_LLVM ON)
else()
    file(READ "${CONTINUUM_LLVM_SDK_SUM_PATH}" llvmSum)
    if(NOT "${llvmSum}" STREQUAL "${CONTINUUM_LLVM_ARCHIVE_SHA256}")
        set(NEED_TO_UPDATE_LLVM ON)
    endif()
endif()

if(NEED_TO_UPDATE_LLVM)

    message(STATUS "Downloading llvm...")
    file(DOWNLOAD "${CONTINUUM_LLVM_ARCHIVE_URL}" "${CONTINUUM_LLVM_ARCHIVE_PATH}" EXPECTED_HASH "SHA256=${CONTINUUM_LLVM_ARCHIVE_SHA256}")

    message(STATUS "Extracting llvm...")
    file(ARCHIVE_EXTRACT INPUT "${CONTINUUM_LLVM_ARCHIVE_PATH}" DESTINATION "${CONTINUUM_LLVM_SDK_DESTINATION_PATH}")

    file(WRITE "${CONTINUUM_LLVM_SDK_SUM_PATH}" "${CONTINUUM_LLVM_ARCHIVE_SHA256}")

endif()


set(LLVM_DIR "${CONTINUUM_LLVM_SDK_PATH}/lib/cmake/llvm")
set(Clang_DIR "${CONTINUUM_LLVM_SDK_PATH}/lib/cmake/clang")

find_package(LLVM CONFIG REQUIRED)
find_package(Clang CONFIG REQUIRED)